"""
tasks.py - MSME Payment Dispute OpenEnv Tasks
Three tasks of increasing difficulty.
"""
import random

TASK1_SCENARIOS = [
    {"id":"t1_001","email":{"subject":"Invoice #1042 not paid for 45 days","body":"We raised Invoice #1042 for Rs. 80,000 on 1st March 2024. Payment was due by 31st March. It is now 45 days overdue and we have not received any payment despite three reminders. Please clear the dues immediately."},"label":"delayed_payment"},
    {"id":"t1_002","email":{"subject":"Only partial amount received against Invoice #2201","body":"We sent Invoice #2201 for Rs. 1,50,000 to your company on 15th February 2024. You have paid only Rs. 60,000 so far. The remaining Rs. 90,000 has not been received. Kindly settle the balance at the earliest."},"label":"partial_payment"},
    {"id":"t1_003","email":{"subject":"Payment refused without valid reason","body":"We delivered all goods as per Purchase Order #PO-5510 on 10th January 2024. Our invoice for Rs. 2,20,000 was submitted on the same date. Your accounts team has informed us that the payment will not be processed, without providing any valid reason. We formally dispute this refusal."},"label":"payment_denial"},
    {"id":"t1_004","email":{"subject":"Invoice overdue by 60 days - urgent","body":"This is a follow-up for Invoice #3390 worth Rs. 45,000 submitted on 5th January 2024. The due date was 4th February 2024. As of today it is 60 days past due. No payment has been credited to our account. We request immediate clearance."},"label":"delayed_payment"},
    {"id":"t1_005","email":{"subject":"Dispute - invoice paid in part only","body":"Invoice #INV-0089 for Rs. 3,00,000 was issued on 20th March 2024. You have transferred Rs. 1,00,000 to our account. We have not received the remaining Rs. 2,00,000. Please explain the deduction and release the balance amount."},"label":"partial_payment"},
    {"id":"t1_006","email":{"subject":"Unjustified rejection of valid invoice","body":"We provided IT services per contract SOW-2024-07 and raised Invoice #INV-512 for Rs. 95,000 on 28th February 2024. Your team has returned the invoice stating it will not be honoured claiming the work was not completed, which is factually incorrect. We formally reject this denial."},"label":"payment_denial"},
    {"id":"t1_007","email":{"subject":"No response on payment - invoice 90 days old","body":"We are writing regarding Invoice #4402 for Rs. 1,10,000 raised on 1st December 2023. The payment was due on 31st December 2023. Despite multiple calls and emails, no payment has been made and no explanation has been provided. This is now 90 days overdue."},"label":"delayed_payment"},
    {"id":"t1_008","email":{"subject":"Short payment on supply invoice","body":"Please note that Invoice #SUP-2230 for goods worth Rs. 75,000 was submitted on 10th March 2024. We received a payment of Rs. 50,000 on 25th March. The shortfall of Rs. 25,000 has not been credited or explained. Kindly resolve this immediately."},"label":"partial_payment"},
    {"id":"t1_009","email":{"subject":"Invoice #887 unpaid for 30 days","body":"Invoice #887 for consulting services rendered in February 2024 amounting to Rs. 55,000 remains unpaid. Due date was 15th March 2024. Today is 15th April. We have sent two reminders with no response. Please treat this as an urgent payment request."},"label":"delayed_payment"},
    {"id":"t1_010","email":{"subject":"Company refusing to acknowledge our invoice","body":"We completed civil construction work under Contract #CIVIL-44 and raised Invoice #INV-9901 for Rs. 4,50,000 on 1st February 2024. Your company has refused to acknowledge receipt of the invoice and your accounts team states no such vendor is registered. We have all documentation to prove the engagement."},"label":"payment_denial"},
]

TASK2_SCENARIOS = [
    {"id":"t2_001","email":{"subject":"Demand notice - Invoice #1042","body":"M/s Sharma Textiles hereby serves formal notice on M/s Bharat Exports for non-payment of Invoice #1042 amounting to Rs. 80,000. The invoice was raised on 1st March 2024 with a due date of 31st March 2024. As of today 14th April 2024, the amount is 14 days overdue. Immediate payment is demanded."},"ground_truth":{"claimant":"Sharma Textiles","opponent":"Bharat Exports","amount":80000,"due_date":"31st March 2024","days_overdue":14}},
    {"id":"t2_002","email":{"subject":"Legal notice for outstanding dues","body":"This notice is issued by M/s Patel Engineering Works against M/s Sunrise Builders Pvt Ltd for non-payment of Invoice #PE-2201 for Rs. 2,50,000. The invoice was submitted on 1st January 2024, payment due by 31st January 2024. As of 15th April 2024, the amount is 75 days overdue."},"ground_truth":{"claimant":"Patel Engineering Works","opponent":"Sunrise Builders Pvt Ltd","amount":250000,"due_date":"31st January 2024","days_overdue":75}},
    {"id":"t2_003","email":{"subject":"Demand for payment - IT services","body":"M/s TechSoft Solutions issues this notice to M/s Global Retail Ltd for recovery of Rs. 1,20,000 against Invoice #TS-512. Services were rendered as per SOW dated 15th February 2024. Payment was due by 15th March 2024. As of 10th April 2024, the invoice is 26 days past due."},"ground_truth":{"claimant":"TechSoft Solutions","opponent":"Global Retail Ltd","amount":120000,"due_date":"15th March 2024","days_overdue":26}},
    {"id":"t2_004","email":{"subject":"Outstanding payment notice - supply of goods","body":"M/s Verma Packaging hereby demands payment from M/s Metro Foods Pvt Ltd for Invoice #VP-330 of Rs. 65,000. Goods were delivered on 5th February 2024, invoice due by 5th March 2024. Current date is 14th April 2024, making the payment 40 days overdue."},"ground_truth":{"claimant":"Verma Packaging","opponent":"Metro Foods Pvt Ltd","amount":65000,"due_date":"5th March 2024","days_overdue":40}},
    {"id":"t2_005","email":{"subject":"Formal demand - construction invoice unpaid","body":"M/s Rajiv Construction Co. serves this notice upon M/s Capital Infra Ltd for recovery of Rs. 5,00,000 against Invoice #RC-9901. Work was completed by 31st December 2023, payment due by 31st January 2024. As of 14th April 2024, the dues are 74 days overdue."},"ground_truth":{"claimant":"Rajiv Construction Co.","opponent":"Capital Infra Ltd","amount":500000,"due_date":"31st January 2024","days_overdue":74}},
]

TASK3_SCENARIOS = [
    {"id":"t3_001","context":{"claimant":"Sharma Textiles","opponent":"Bharat Exports","amount":80000,"invoice_no":"1042","invoice_date":"1st March 2024","due_date":"31st March 2024","days_overdue":14,"dispute_type":"delayed_payment","evidence":["Invoice copy","Delivery challan","2 email reminders"]},"grading_criteria":{"must_mention":["Sharma Textiles","Bharat Exports","80,000","Invoice #1042"],"legal_elements":["legal action","interest","MSME","demand"],"tone_keywords_bad":["please kindly","if possible","whenever you can"]}},
    {"id":"t3_002","context":{"claimant":"Patel Engineering Works","opponent":"Sunrise Builders Pvt Ltd","amount":250000,"invoice_no":"PE-2201","invoice_date":"1st January 2024","due_date":"31st January 2024","days_overdue":75,"dispute_type":"delayed_payment","evidence":["Invoice copy","Work completion certificate","3 reminder emails"]},"grading_criteria":{"must_mention":["Patel Engineering Works","Sunrise Builders","2,50,000","PE-2201"],"legal_elements":["legal proceedings","interest","MSME Act","notice period"],"tone_keywords_bad":["hope you will","please consider","we humbly request"]}},
    {"id":"t3_003","context":{"claimant":"TechSoft Solutions","opponent":"Global Retail Ltd","amount":120000,"invoice_no":"TS-512","invoice_date":"15th February 2024","due_date":"15th March 2024","days_overdue":26,"dispute_type":"partial_payment","evidence":["Invoice copy","SOW document","Payment receipt for partial amount"]},"grading_criteria":{"must_mention":["TechSoft Solutions","Global Retail","1,20,000","TS-512"],"legal_elements":["legal action","balance amount","MSME","demand"],"tone_keywords_bad":["sorry to bother","if convenient","as a favour"]}},
]

def get_scenario(task_id: int, seed: int = None) -> dict:
    rng = random.Random(seed)
    if task_id == 1: return rng.choice(TASK1_SCENARIOS)
    elif task_id == 2: return rng.choice(TASK2_SCENARIOS)
    elif task_id == 3: return rng.choice(TASK3_SCENARIOS)
    else: raise ValueError(f"Invalid task_id: {task_id}")

# FIX 2: 5 additional Task 3 scenarios (total: 8)
TASK3_SCENARIOS_EXTRA = [
    {"id":"t3_004","context":{"claimant":"Verma Packaging","opponent":"Metro Foods Pvt Ltd","amount":65000,"invoice_no":"VP-330","invoice_date":"5th February 2024","due_date":"5th March 2024","days_overdue":40,"dispute_type":"delayed_payment","evidence":["Invoice copy","Delivery receipt","WhatsApp reminders"]},"grading_criteria":{"must_mention":["Verma Packaging","Metro Foods","65,000","VP-330"],"legal_elements":["legal action","MSME","interest","demand"],"tone_keywords_bad":["please kindly","if possible","sorry to disturb"]}},
    {"id":"t3_005","context":{"claimant":"Rajiv Construction Co.","opponent":"Capital Infra Ltd","amount":500000,"invoice_no":"RC-9901","invoice_date":"31st December 2023","due_date":"31st January 2024","days_overdue":74,"dispute_type":"payment_denial","evidence":["Invoice copy","Signed work completion certificate","Site photographs","Contract agreement"]},"grading_criteria":{"must_mention":["Rajiv Construction","Capital Infra","5,00,000","RC-9901"],"legal_elements":["legal proceedings","MSME Act","interest","arbitration"],"tone_keywords_bad":["humbly request","if you can","whenever convenient"]}},
    {"id":"t3_006","context":{"claimant":"Sri Lakshmi Garments","opponent":"Fashion Hub Retail Ltd","amount":175000,"invoice_no":"SLG-441","invoice_date":"10th January 2024","due_date":"10th February 2024","days_overdue":63,"dispute_type":"delayed_payment","evidence":["Invoice copy","Lorry receipt","3 written reminders"]},"grading_criteria":{"must_mention":["Sri Lakshmi","Fashion Hub","1,75,000","SLG-441"],"legal_elements":["MSME","interest","legal action","demand notice"],"tone_keywords_bad":["please try","hope you will","at your convenience"]}},
    {"id":"t3_007","context":{"claimant":"Gupta Auto Parts","opponent":"National Motors Pvt Ltd","amount":230000,"invoice_no":"GAP-882","invoice_date":"20th February 2024","due_date":"20th March 2024","days_overdue":25,"dispute_type":"partial_payment","evidence":["Invoice copy","Bank statement showing partial credit","Purchase order copy"]},"grading_criteria":{"must_mention":["Gupta Auto","National Motors","2,30,000","GAP-882"],"legal_elements":["balance amount","MSME","interest","legal notice"],"tone_keywords_bad":["kindly do the needful","please oblige","if possible"]}},
    {"id":"t3_008","context":{"claimant":"Meenakshi Textiles","opponent":"Southern Exports Ltd","amount":320000,"invoice_no":"MT-7721","invoice_date":"1st November 2023","due_date":"1st December 2023","days_overdue":135,"dispute_type":"delayed_payment","evidence":["Invoice copy","Shipping bill","6 reminder emails","Legal notice draft"]},"grading_criteria":{"must_mention":["Meenakshi Textiles","Southern Exports","3,20,000","MT-7721"],"legal_elements":["MSME Facilitation Council","compound interest","legal proceedings","final notice"],"tone_keywords_bad":["we hope","please consider","if possible"]}},
]

# Merge into main list
TASK3_SCENARIOS = TASK3_SCENARIOS + TASK3_SCENARIOS_EXTRA
